export const ADD_TODO = "ADD_TODO";
export const EDIT_TODO = "EDIT_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const TOGGLE_TASK_COMPLETION= "TOGGLE_TODO";
export const UPDATE_ALARM_STATUS = "UPDATE_ALARM_STATUS";
